### ISSUE TITLE
Notion import is failing

### ISSUE THREAD

**Issue by DarioAhdoot** [anyproto/anytype-heart#339] opened 2023-08-27 12:08 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Installed app today and tried to import data from notion, but it errored with a generic error telling me to contact you.

I created an integration on Notion to import, checked all options on the Capabilities tab, saved the integration:
![image](https://github.com/anyproto/anytype-ts/assets/4357102/bdc2c23e-7adf-4244-b3c3-302fdc2047a5)

I copied the integration key and pasted it into the app's Notion integration screen. Clicked import data and got to this screen:
<img width="656" alt="image" src="https://github.com/anyproto/anytype-ts/assets/4357102/081dc09c-b9c1-403c-83cc-1cf0ffb263aa">

When I clicked Proceed, I immediately got the following error:
<img width="424" alt="image" src="https://github.com/anyproto/anytype-ts/assets/4357102/cd46c044-b706-474b-a8e9-ff15753eb577">

### Expected Behavior

I would expect the import to work, or fail with a more helpful error

### Steps To Reproduce

1. Click on Profile on top/left of sidebar
2. Click on Import to space
3. Click on Notion
4. Paste in integration key/secret.
5. Observe immediate failure

### Environment

```markdown
- OS: macOS Ventura 13.5
- Version: 0.34.3
```

### Anything else?

I've attached images above. There are no logs that I am aware of. If you let me know where they are stored, will provide.

**Comment by ra3orblade** [comment] 2023-08-28 12:35
Duplicate of https://github.com/anyproto/anytype-heart/issues/340

**Closed by ra3orblade** 2023-08-28 12:35 UTC
Labels: bug

**Comment by DarioAhdoot** [comment] 2023-08-28 12:37
Ugh. No idea how I ended up posting it in here instead of the anytype-ts. Sorry ¯\_(ツ)_/¯
