### ISSUE TITLE
if you paste code in code block will get extra blank lines

### ISSUE THREAD

**Issue by ruxtain** [anyproto/anytype-heart#287] opened 2023-08-09 01:33 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

if you paste code in code block will get extra blank lines, I have to manually delete the extra lines which is really annoying.

### Expected Behavior

Paste the code as it is. Don't add anything needless.

### Steps To Reproduce

1. open a note.
2. create a code block
3. copy code from somewhere, such as sublime text 4 or notepad
4. paste it into the code block
5. there you go, extra blank lines are there

### Environment

```markdown
- OS:Windows
- Version:11
```

**Comment by fuksman** [comment] 2023-08-20 10:39
Duplicate of #321

**Closed by fuksman** 2023-08-20 10:39 UTC
Labels: bug
